### PR TITLE
Item Search

### PR DESCRIPTION
**Pull request by kphoenix137**
Adds item searching functionality for things beyond Puzzler. `puzzler.cpp` currently remains intact, but upon completion of this PR it will be removed with `item.cpp` taking its place.

### CODE REVIEW

**Comment by AJenbo** [comment]
@kphoenix137 can you approve and merge this?

**Comment by kphoenix137** [comment]
> @kphoenix137 can you approve and merge this?

Doesn't work atm. Gonna fix it tonight

**Comment by AJenbo** [comment]
... my point is, why is this a PR from your self for your self by your self :D

**Comment by kphoenix137** [comment]
> ... my point is, why is this a PR from your self for your self by your self :D

So I can see the exact changes I made more easily as I submit commits. I'll make a devilution branch and move my changes there now

**Pull request merged**
